#!/usr/bin/env bash
# Configures an Ubuntu server with custom host resolutions
awk '{if($2=="localhost") $1="127.0.0.2"; print}' /etc/hosts > /tmp/hosts.tmp
echo "8.8.8.8 facebook.com" >> /tmp/hosts.tmp
cp /tmp/hosts.tmp /etc/hosts
