#!/usr/bin/env bash
# Configures an Ubuntu server with custom host resolutions
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
